const fs=require('fs'),vm=require('vm');
const src=fs.readFileSync('questions.js','utf8');
const box={}; vm.createContext(box); vm.runInContext(src+'\nthis.d=examDuration;this.q=questions;',box);
const d=box.d, bank=box.q;
const num=s=>/[0-9]/.test(String(s));
const N=s=>String(s||'').replace(/\s+/g,' ').trim();
const U={Joule:'unit of energy or work',Watt:'unit of power',Newton:'unit of force',Pascal:'unit of pressure',Volt:'unit of potential difference',Ohm:'unit of resistance',Ampere:'unit of electric current',Coulomb:'unit of electric charge',Dioptres:'unit of lens power',Tesla:'unit of magnetic flux density',Becquerel:'SI unit of radioactivity',Curie:'older non-SI unit of radioactivity',Roentgen:'older unit linked to X-ray exposure',Gray:'SI unit of absorbed radiation dose',Weber:'unit of magnetic flux',Henry:'unit of inductance',Farad:'unit of capacitance',Kelvin:'absolute temperature scale',Celsius:'temperature scale'};
const I={Barometer:'measures atmospheric pressure',Thermometer:'measures temperature',Hygrometer:'measures relative humidity',Hydrometer:'measures the density or relative density of liquids',Manometer:'measures pressure in enclosed fluids',Calorimeter:'is used for heat measurements',Anemometer:'measures wind speed',Ammeter:'measures electric current',Voltmeter:'measures potential difference',Galvanometer:'detects very small currents', 'Geiger-Muller counter':'detects ionizing radiation'};
const L={"Newton's 1st Law":'the law of inertia',"Newton's 2nd Law":'the law relating force to rate of change of momentum',"Newton's 3rd Law":'the law of action and reaction',"Hooke's Law":'the law relating force to extension in an elastic spring',"Ohm's law":'the law relating current, voltage, and resistance',"Charles's Law":'the law relating gas volume to absolute temperature at constant pressure',"Boyle's Law":'the law relating gas pressure to volume at constant temperature',"Archimedes' principle":'the principle of upthrust',"Pascal's principle":'the principle of transmission of pressure in fluids',"Coulomb's":'the law of force between electric charges'};
const T={Speed:'the rate of change of distance',Acceleration:'the rate of change of velocity',Velocity:'the rate of change of displacement',Force:'a push or pull equal to mass times acceleration',Momentum:'mass multiplied by velocity',Power:'the rate of doing work',Potential Difference:'the work done per unit charge',Resistance:'opposition to current flow',Capacitance:'ability to store charge',Inertia:'resistance to change in motion',Mass:'amount of matter and a scalar quantity',Density:'mass per unit volume',Viscosity:'resistance of a fluid to flow',Capillarity:'rise or fall of a liquid in a narrow tube',Cohesion:'attraction between like molecules',Conduction:'heat transfer through direct contact',Convection:'heat transfer by bulk motion of fluids',Radiation:'heat transfer by electromagnetic waves',Reflection:'bouncing back of waves from a surface',Refraction:'bending of waves when speed changes in a new medium',Dispersion:'splitting of white light into colours',Diffraction:'bending of waves around edges or obstacles',Interference:'overlapping of waves to produce reinforcement or cancellation',Rectilinear propagation:'straight-line travel of light',Wavelength:'distance between successive points in phase',Frequency:'number of vibrations per second',Amplitude:'maximum displacement from the mean position'};
const D={Generator:'converts mechanical energy to electrical energy',Motor:'converts electrical energy to mechanical energy',Transformer:'changes AC voltage',Rectifier:'converts AC to DC',Capacitor:'stores electric charge',Electromagnet:'a magnet produced by electric current',Commutator:'reverses current in a DC motor armature',Retina:'light-sensitive layer where the eye forms images',Concave:'curves inward',Convex:'bulges outward',Silicon:'a common semiconductor material',Electron:'a negatively charged particle',Proton:'a positively charged particle',Neutron:'a neutral particle',Gamma:'electromagnetic radiation from the nucleus','Gamma rays':'highly penetrating electromagnetic radiation','Alpha particle':'a helium nucleus','Beta particle':'a fast electron or positron',Sound:'a mechanical wave that needs a material medium','Longitudinal waves':'waves whose vibrations are parallel to the direction of travel','Transverse waves':'waves whose vibrations are perpendicular to the direction of travel'};
function wrong(q,o,a){const t=q.text;if(q.id==='P8'){const m={"2J":'it could come from dividing 10 by 5 instead of multiplying force by distance.',"15J":'it could come from adding 10 and 5, but work is not found by addition here.',"0.5J":'it could come from reversing the numbers or using the wrong operation.'};return `"${o}" is incorrect because ${m[o]}`}
if(q.id==='P22'){const m={"100K":'100°C is not 100 K because Kelvin and Celsius do not start at the same zero point.',"273K":'273 K is 0°C, which is the freezing point of water, not the boiling point.',"0K":'0 K is absolute zero, far below the temperature at which water boils.'};return `"${o}" is incorrect because ${m[o]}`}
if(q.id==='P105'){const m={"30°":'using sin c = 1/n with n = v2 does not give 30°.',"60°":'60° would require a smaller refractive index than the one given.',"90°":'90° would mean the ray travels along the boundary, not the critical angle for this case.'};return `"${o}" is incorrect because ${m[o]}`}
if(q.id==='P125'){const m={"8O":'that is the series result, not the parallel result.',"4O":'parallel connection must reduce the total resistance below the smallest resistor.',"1O":'that would be too small for just two equal 4 O resistors in parallel.'};return `"${o}" is incorrect because ${m[o]}`}
if(U[o])return `"${o}" is incorrect because it is the ${U[o]}, so it answers a different measurement question.`;
if(I[o])return `"${o}" is incorrect because it ${I[o]}, so it is not the instrument needed here.`;
if(L[o])return `"${o}" is incorrect because it describes ${L[o]}, not the exact law tested in this question.`;
if(T[o])return `"${o}" is incorrect because it means ${T[o]}, which is different from what the question asks for.`;
if(D[o])return `"${o}" is incorrect because it ${D[o]}, so it does not fit this question.`;
if(num(o)&&num(a))return `"${o}" is incorrect because the correct value or calculation leads to ${a}, not ${o}.`;
return `"${o}" is incorrect because it does not match the definition, law, device, or formula being tested here.`;}
function main(q){const t=q.text,a=q.answer,l=t.toLowerCase();
if(q.id==='P8')return `"${a}" is correct because work done is calculated with the formula W = F × d. Here, F = 10 N and d = 5 m, so W = 10 × 5 = 50 J. A joule is the SI unit of work, so the unit also confirms the answer. This question teaches that work depends on both the size of the force and the distance moved in the force's direction.`;
if(q.id==='P22')return `"${a}" is correct because water boils at 100°C under normal atmospheric pressure, and Kelvin temperature is found by adding 273 to the Celsius value. So 100 + 273 = 373 K. Kelvin is called an absolute scale because it starts from absolute zero, not from the freezing point of water. This is why boiling point in Kelvin is higher than the same temperature written in Celsius.`;
if(q.id==='P105')return `"${a}" is correct because the critical angle c is related to refractive index n by sin c = 1/n when light travels from a denser to a rarer medium. Here n = v2, so sin c = 1/v2, and the angle whose sine is 1/v2 is 45°. This is an important optics result because total internal reflection begins when the angle of incidence is greater than this critical angle. Learning this formula helps students connect refractive index with light behavior at boundaries.`;
if(q.id==='P125')return `"${a}" is correct because for resistors in parallel, 1/R = 1/R1 + 1/R2. So 1/R = 1/4 + 1/4 = 2/4 = 1/2, which gives R = 2 O. Parallel connection always reduces the total resistance below the smallest individual resistor, and that is exactly what happens here. This is a useful check students can use even before finishing the calculation.`;
if(/what is the si unit of/i.test(t))return `"${a}" is correct because it is the SI unit for the quantity named in the question. The SI system is the internationally accepted measurement system used in Physics, so every physical quantity has a standard unit. Knowing the correct unit helps students interpret formulas correctly, because the unit tells you what kind of quantity you are dealing with. If you choose the wrong unit, you are really describing a different physical idea.`;
if(/the unit of/i.test(t))return `"${a}" is correct because it is the standard unit for the physical quantity mentioned. In Physics, units are not decoration; they show what is being measured and help us check whether a formula or answer makes sense. A student who knows both the quantity and its unit is much less likely to confuse related ideas. That is why unit questions are so important.`;
if(/instrument used to measure|used to measure/i.test(t))return `"${a}" is correct because it is the instrument designed for that specific measurement. In science, instruments are chosen according to the quantity being observed, so using the wrong instrument gives the wrong kind of information. Students should learn each measuring instrument together with the quantity it measures. That makes practical physics much easier to remember.`;
if(/which law states|this is:/i.test(t))return `"${a}" is correct because it is the law or principle that exactly describes the situation in the question. A physical law is a concise statement of a repeated relationship in nature, so you must match the wording of the law to the phenomenon described. This helps students move beyond memorizing names and start understanding what each law actually explains. The best answer is the one whose statement fits the situation fully.`;
if(/rate of change of displacement/i.test(t))return `"${a}" is correct because velocity is defined as the rate of change of displacement with time. Displacement includes direction, so velocity is a vector quantity, unlike speed which only uses distance. This question helps students see that even similar-looking motion terms are not identical. Paying attention to the exact word used in the definition is the key to getting it right.`;
if(/product of mass and velocity/i.test(t))return `"${a}" is correct because momentum is defined as mass multiplied by velocity. In symbols, p = mv. Momentum tells us how difficult it is to stop a moving body, which is why a fast heavy object is harder to stop than a light slow one. This idea is central in collisions and motion problems.`;
if(/scalar quantity/i.test(t))return `"${a}" is correct because a scalar quantity has magnitude only and no direction. Mass tells us how much matter an object contains, but it does not point in any direction, so it is scalar. This question helps students separate scalar quantities from vector quantities such as force and velocity, which need both size and direction to be fully described. That distinction appears throughout mechanics.`;
if(/energy possessed by a body due to its motion/i.test(t))return `"${a}" is correct because kinetic energy is the energy a body has because it is moving. The faster an object moves, or the greater its mass, the greater its kinetic energy. You see this in everyday life when a moving bicycle or car can do work because of its motion. This is different from potential energy, which depends on position or stored conditions.`;
if(/resist change in its state of motion/i.test(t))return `"${a}" is correct because inertia is the property of matter that makes a body resist any change in its state of rest or uniform motion. A heavy object usually shows more inertia than a light one because it is harder to start or stop. This idea is closely related to Newton's First Law. Understanding inertia helps explain why passengers jerk forward when a moving vehicle stops suddenly.`;
if(/mechanical advantage/i.test(t))return `"${a}" is correct because mechanical advantage tells us how much a machine multiplies force, and it is defined as Load ÷ Effort. If a small effort lifts a large load, the machine has a high mechanical advantage. This helps students see why simple machines are useful in everyday work. The definition must be remembered exactly because reversing the ratio gives the wrong idea.`;
if(/velocity ratio/i.test(t)&&/inclined plane/i.test(t))return `"${a}" is correct because the velocity ratio of an inclined plane is the distance moved by the effort divided by the distance moved by the load. For an inclined plane, that becomes length ÷ height, and from trigonometry length ÷ height = 1/sin ?. This formula shows how geometry and machines are linked in physics. The steeper the plane, the smaller the advantage gained.`;
if(/velocity ratio of 1/i.test(t))return `"${a}" is correct because a single fixed pulley changes the direction of the effort but does not multiply the distance moved. That means the effort moves the same distance as the load, so the velocity ratio is 1. It is useful when you want convenience rather than force multiplication. This is why it is simple but not force-saving in the ideal case.`;
if(/center of gravity/i.test(t))return `"${a}" is correct because a uniform circular hoop is symmetrical, so its weight is evenly distributed around the center. The center of gravity is the point through which the whole weight may be considered to act. In a uniform hoop, that point is exactly at the center. Symmetry is often the quickest way to answer center-of-gravity questions.`;
if(/pressure is defined/i.test(t))return `"${a}" is correct because pressure is the force acting per unit area. In symbols, P = F/A. This means the same force produces more pressure when it acts on a smaller area, which is why sharp knives cut better than blunt ones. The definition is one of the most useful in mechanics and fluid physics.`;
if(/fundamental quantity/i.test(t))return `"${a}" is correct because fundamental quantities are basic physical quantities that are not derived from other physical quantities. Length is one of the standard base quantities in measurement. Other quantities like speed, force, and volume are derived from combinations of base quantities. Students should always separate base quantities from derived ones.`;
if(/dimension of velocity/i.test(t))return `"${a}" is correct because velocity is distance per unit time. Distance has dimension L and time has dimension T, so velocity has dimension LT?¹. Dimensional analysis helps students check whether formulas are physically meaningful. It is a powerful tool for spotting mistakes in equations.`;
if(/area under a velocity-time graph/i.test(t))return `"${a}" is correct because the area under a velocity-time graph is velocity multiplied by time, and velocity × time gives displacement or distance. This means graphs can carry physical meaning, not just visual information. Students should remember that slope and area on graphs often represent different quantities. Here, the area tells you how far the object moved.`;
